// <auto-generated />
using System;
using FreelancersApi.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(FreelancerContext))]
    [Migration("20260525164852_AddAvailableUntilToFreelancerUpdate-Database")]
    partial class AddAvailableUntilToFreelancerUpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryFreelancer", b =>
                {
                    b.Property<int>("SkillFreelancersFreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SkillFreelancersFreelancerId", "SkillsCategoryId");

                    b.HasIndex("SkillsCategoryId");

                    b.ToTable("FreelancerSkills", (string)null);
                });

            modelBuilder.Entity("CategoryFreelancer1", b =>
                {
                    b.Property<int>("SpecializationFreelancersFreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationsCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SpecializationFreelancersFreelancerId", "SpecializationsCategoryId");

                    b.HasIndex("SpecializationsCategoryId");

                    b.ToTable("FreelancerSpecializations", (string)null);
                });

            modelBuilder.Entity("CategoryJob", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredSkillsCategoryId")
                        .HasColumnType("int");

                    b.HasKey("JobId", "RequiredSkillsCategoryId");

                    b.HasIndex("RequiredSkillsCategoryId");

                    b.ToTable("JobRequiredSkills", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Repository.Entities.Freelancer", b =>
                {
                    b.Property<int>("FreelancerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreelancerId"));

                    b.Property<int>("AvailableHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FreelancerId");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Freelancers");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int?>("AssignedFreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxPayPerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequiredHours")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.HasIndex("AssignedFreelancerId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Repository.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClientInvite")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("JobId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Repository.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryFreelancer", b =>
                {
                    b.HasOne("Repository.Entities.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("SkillFreelancersFreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("SkillsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryFreelancer1", b =>
                {
                    b.HasOne("Repository.Entities.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("SpecializationFreelancersFreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("SpecializationsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryJob", b =>
                {
                    b.HasOne("Repository.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("RequiredSkillsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repository.Entities.Category", b =>
                {
                    b.HasOne("Repository.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Repository.Entities.Freelancer", b =>
                {
                    b.HasOne("Repository.Entities.Category", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithOne("FreelancerProfile")
                        .HasForeignKey("Repository.Entities.Freelancer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.HasOne("Repository.Entities.Freelancer", "AssignedFreelancer")
                        .WithMany("JobsInProgress")
                        .HasForeignKey("AssignedFreelancerId");

                    b.HasOne("Repository.Entities.User", "Client")
                        .WithMany("PostedJobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Category", "MainCategory")
                        .WithMany("Jobs")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedFreelancer");

                    b.Navigation("Client");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Repository.Entities.Proposal", b =>
                {
                    b.HasOne("Repository.Entities.Freelancer", "Freelancer")
                        .WithMany("ProposalsSubmitted")
                        .HasForeignKey("FreelancerId")
                        .IsRequired();

                    b.HasOne("Repository.Entities.Job", "Job")
                        .WithMany("Proposals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Repository.Entities.Rating", b =>
                {
                    b.HasOne("Repository.Entities.Freelancer", "Freelancer")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Category", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Repository.Entities.Freelancer", b =>
                {
                    b.Navigation("JobsInProgress");

                    b.Navigation("ProposalsSubmitted");

                    b.Navigation("RatingsReceived");
                });

            modelBuilder.Entity("Repository.Entities.Job", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Navigation("FreelancerProfile");

                    b.Navigation("PostedJobs");

                    b.Navigation("RatingsGiven");
                });
#pragma warning restore 612, 618
        }
    }
}
